version: "3.8"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/usbdrive/plex/config:/config
      - /mnt/usbdrive/plex/tvseries:/tv
      - /mnt/usbdrive/plex/movies:/movies
    restart: unless-stopped